"""Prove the whole data pipeline works, end to end, without any hardware.

WHAT THIS DOES NOT PROVE
------------------------
This builds captures whose numbers are invented, and invents them so that the
two categories differ. A model trained on them will score well. That says
NOTHING about whether WiFi channel state information can actually tell metal
from non-metal - the difference was put there on purpose.

What it does prove is that every pipe between the board and a trained model is
connected and the right shape: that a capture written in the real CSV format
survives filtering, that features come out of it, that dataset_report accepts
the metadata, and that train_classifier will produce a model and score it.

So: a pass means "when real data arrives, the machinery will carry it". A pass
means nothing at all about the science. Those are different claims and this
file will not blur them.

    python pipeline_selftest.py

Exits non-zero if any stage fails.
"""

import csv
import json
import math
import random
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent

# The real CSV header, as collect_burst.py writes it. Kept as one string on
# purpose: if the firmware or the collector ever disagree with this, the test
# should fail rather than quietly adapt.
HEADERS = [
    "type", "id", "mac", "rssi", "rate", "sig_mode", "mcs", "bandwidth",
    "smoothing", "not_sounding", "aggregation", "stbc", "fec_coding", "sgi",
    "noise_floor", "ampdu_cnt", "channel", "secondary_channel", "local_timestamp",
    "ant", "sig_len", "sig_mode", "len", "first_word", "data",
]

# Lengths seen in this project's own real captures.
CSI_LEN = 128
RATE_HZ = 20
DURATION_S = 10


def csi_row(index, timestamp_us, rssi, amplitude, noise):
    """One row in the exact shape the receiver prints."""
    values = []
    for carrier in range(CSI_LEN // 2):
        # A gently shaped response plus noise. The shape is arbitrary; only its
        # format matters here.
        base = amplitude * math.sin(carrier / 9.0)
        values.append(int(base + random.gauss(0, noise)))
        values.append(int(base * 0.6 + random.gauss(0, noise)))
    data = "[" + ",".join(str(v) for v in values) + "]"
    return [
        "CSI_DATA", index, "5c:01:3b:6b:b0:95", rssi, 11, 0, 0, 0, 0, 0, 0, 0,
        0, 0, -95, 0, 11, 0, timestamp_us, 0, 37, 0, CSI_LEN, 1, data,
    ]


def write_run(directory, category, object_name, run_index, amplitude, rssi):
    """Writes one capture and its metadata, the way a finished run looks."""
    directory.mkdir(parents=True, exist_ok=True)
    stem = f"{object_name}_{category}_{DURATION_S}s_{RATE_HZ}hz_run{run_index:04d}"
    csv_path = directory / f"{stem}.csv"

    samples = DURATION_S * RATE_HZ
    transmitter_packets = samples          # a perfect run: every packet captured
    step_us = 1_000_000 // RATE_HZ

    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(HEADERS)
        for index in range(samples):
            writer.writerow(csi_row(index, 9_000_000 + index * step_us,
                                    rssi + random.randint(-1, 1), amplitude, 2.0))

    ratio = samples / transmitter_packets
    metadata = {
        "schema_version": 2,
        "run_id": stem,
        "category": category,
        "object_name": object_name,
        "description": "generated by pipeline_selftest.py - NOT a real capture",
        "synthetic": True,
        "duration_ms": DURATION_S * 1000,
        "rate_hz": RATE_HZ,
        "channel": 11,
        "samples": samples,
        "transmitter_packets": transmitter_packets,
        "transmitter_failures": 0,
        "complete": True,
        "raw_data_stored": True,
        "capture_status": "success",
        "receiver_capture_armed": True,
        "receiver_capture_stopped": True,
        "receiver_queue_drops": 0,
        # The coverage figure is re-derived by dataset_report and compared with
        # a tolerance of one part in a million, so it is written with enough
        # digits to survive that. Six decimal places is not always enough.
        "sample_coverage_ratio": float(f"{ratio:.9f}"),
        "sample_coverage_acceptable": ratio >= 0.75,
        "processing_status": "not_run",
        "derived_files": [],
    }
    csv_path.with_suffix(".json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    return csv_path


def run(script, *args):
    """Runs one of the real tools exactly as a person would."""
    command = [sys.executable, str(HERE / script), *[str(a) for a in args]]
    result = subprocess.run(command, capture_output=True, text=True)
    return result


def process_run(csv_path):
    """Filter and extract features, then mark the metadata the way the
    collector does once processing has succeeded."""
    filtered = csv_path.with_name(f"{csv_path.stem}.filtered.csv")
    features = filtered.with_name(f"{filtered.stem}.features.json")

    result = run("process_csi.py", csv_path)
    if result.returncode != 0:
        return False, f"process_csi failed: {result.stderr.strip() or result.stdout.strip()}"

    result = run("extract_features.py", filtered)
    if result.returncode != 0:
        return False, f"extract_features failed: {result.stderr.strip() or result.stdout.strip()}"

    metadata_path = csv_path.with_suffix(".json")
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    metadata["processing_status"] = "success"
    metadata["derived_files"] = [str(filtered), str(features)]
    metadata_path.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    return True, None


def build_dataset(root, plan):
    """plan: list of (category, object_name, amplitude, rssi, how_many)"""
    for category, object_name, amplitude, rssi, count in plan:
        for index in range(count):
            csv_path = write_run(root / category, category, object_name,
                                 index + 1, amplitude, rssi)
            ok, why = process_run(csv_path)
            if not ok:
                return False, why
    return True, None


def main():
    random.seed(20260914)
    failures = []
    workspace = Path(tempfile.mkdtemp(prefix="wisense_selftest_"))

    try:
        train_dir = workspace / "train"
        test_dir = workspace / "test"

        # The two splits deliberately use DIFFERENT objects. train_classifier
        # refuses to run if a (category, object_name) pair appears in both, and
        # that guard is one of the things being tested here.
        print("1. building synthetic captures and running the filter/feature tools")
        ok, why = build_dataset(train_dir, [
            ("metal",     "mug",    60.0, -41, 4),
            ("non_metal", "bottle", 30.0, -48, 4),
        ])
        if not ok:
            failures.append(f"training set: {why}")
        ok, why = build_dataset(test_dir, [
            ("metal",     "tin",  58.0, -42, 2),
            ("non_metal", "book", 32.0, -47, 2),
        ])
        if not ok:
            failures.append(f"test set: {why}")

        if failures:
            raise SystemExit(report(failures, workspace))

        print("2. dataset_report on the training set")
        result = run("dataset_report.py", "--data-dir", train_dir)
        if result.returncode != 0:
            failures.append(f"dataset_report exited {result.returncode}: {result.stderr.strip()}")
        else:
            report_json = json.loads(result.stdout)
            if not report_json.get("training_ready"):
                failures.append("dataset_report says the training set is not ready")
            if report_json.get("invalid_runs"):
                failures.append(f"invalid runs: {json.dumps(report_json['invalid_runs'], indent=2)}")
            else:
                print(f"   {len(report_json['valid_runs'])} valid runs, categories "
                      f"{dict(report_json['categories'])}")

        print("3. train_classifier, held-out test set")
        model_path = workspace / "model.json"
        result = run("train_classifier.py",
                     "--data-dir", train_dir,
                     "--test-data-dir", test_dir,
                     "--output", model_path)
        if result.returncode != 0:
            failures.append(f"training failed: {result.stderr.strip() or result.stdout.strip()}")
        elif not model_path.exists():
            failures.append("training reported success but wrote no model")
        else:
            model = json.loads(model_path.read_text(encoding="utf-8"))
            accuracy = model["evaluation"]["accuracy"]
            print(f"   model written, {model['algorithm']}, "
                  f"test accuracy {accuracy:.3f} on {model['evaluation']['total']} runs")
            for key in ("scaler", "classes", "features", "evaluation", "thresholds"):
                if key not in model:
                    failures.append(f"model is missing '{key}'")

            # The gate screen shows three levels, so the model has to produce a
            # number, not just a label. Check it exists and points the right
            # way: metal runs should score above non-metal ones.
            scores = model["evaluation"].get("scores")
            if not scores:
                failures.append("model evaluation has no per-run metal scores - "
                                "the orange CHECK band has nothing to drive it")
            else:
                metal = [r["metal_score"] for r in scores if r["actual"] == "metal"]
                other = [r["metal_score"] for r in scores if r["actual"] == "non_metal"]
                print("   metal scores " + ", ".join(f"{v:.1f}" for v in sorted(metal)) +
                      "   non-metal " + ", ".join(f"{v:.1f}" for v in sorted(other)))
                if not metal or not other:
                    failures.append("scores are missing one of the two classes")
                elif min(metal) <= max(other):
                    failures.append("metal runs did not all score above non-metal runs - "
                                    "the score is not ordered the way the bands assume")
                for row in scores:
                    if not 0.0 <= row["metal_score"] <= 100.0:
                        failures.append(f"metal score out of range: {row}")

        print("4. the leakage guard refuses testing on the training directory")
        result = run("train_classifier.py",
                     "--data-dir", train_dir,
                     "--test-data-dir", train_dir,
                     "--output", workspace / "leaky.json")
        if result.returncode == 0:
            failures.append("training the same directory against itself was ALLOWED - "
                            "the guard against testing on training data is not working")
        else:
            print(f"   refused, as it should: {result.stderr.strip().splitlines()[-1]}")

        # The guard that matters once real data exists. Two different folders
        # are not enough: the same object appearing in both splits means the
        # model is scored on something it was shown. This is the check that
        # shapes how collection has to be planned, so it is worth proving.
        print("5. the leakage guard refuses the same object in both splits")
        leaky_dir = workspace / "leaky_test"
        shutil.copytree(test_dir, leaky_dir)
        copied = write_run(leaky_dir / "metal", "metal", "mug", 99, 60.0, -41)
        ok, why = process_run(copied)
        if not ok:
            failures.append(f"could not build the overlapping case: {why}")
        else:
            result = run("train_classifier.py",
                         "--data-dir", train_dir,
                         "--test-data-dir", leaky_dir,
                         "--output", workspace / "leaky2.json")
            if result.returncode == 0:
                failures.append("an object present in BOTH splits was ALLOWED - "
                                "the overlap guard is not working, and any accuracy "
                                "figure from this pipeline would be inflated")
            else:
                print(f"   refused, as it should: {result.stderr.strip().splitlines()[-1]}")

        raise SystemExit(report(failures, workspace))

    finally:
        shutil.rmtree(workspace, ignore_errors=True)


def report(failures, workspace):
    print()
    if failures:
        print("PIPELINE SELF-TEST FAILED")
        for failure in failures:
            print(f"  - {failure}")
        return 1

    print("PIPELINE SELF-TEST PASSED")
    print()
    print("  Every stage between a capture and a scored model works:")
    print("  filter -> features -> dataset check -> train -> evaluate,")
    print("  and the guard against testing on training data holds.")
    print()
    print("  This says NOTHING about whether CSI can detect metal. The")
    print("  difference between the two categories was invented by this")
    print("  script. Only real captures can answer that.")
    return 0


if __name__ == "__main__":
    main()
