[platformio]
src_dir = main
build_dir = .pio/build
workspace_dir = .pio

[env:esp32dev]
platform = espressif32@7.0.0
board = esp32dev
framework = arduino
upload_speed = 460800
monitor_speed = 115200
monitor_filters = direct
